use super::{CodegenError, Object, Value};

const HEADER_COMMENT: &str =
    "-- This file was @generated by Runway. It is not intended for manual editing.";

pub(super) fn generate_luau(tree: &Value) -> Result<String, CodegenError> {
    let Value::Object(root) = tree else { panic!() };

    let mut s = String::new();
    s.push_str(HEADER_COMMENT);
    s.push_str("\nreturn ");
    s.push_str(&format_object(root, 0));
    s.push_str("\n");

    Ok(s)
}

fn format_object(obj: &Object, indent_level: usize) -> String {
    let indent = "\t".repeat(indent_level);
    let indent_plus1 = "\t".repeat(indent_level + 1);

    let mut s = String::new();
    s.push_str("{\n");

    let mut iter = obj.0.iter().peekable();

    while let Some((k, v)) = iter.next() {
        s.push_str(&(indent_plus1.clone() + "[" + &format_string(k) + "] = "));

        match v {
            Value::Object(subobj) => {
                s.push_str(&format_object(&subobj, indent_level + 1));
                s.push_str(",\n");
            }
            Value::Id(id) => {
                s.push_str(&format_string(id));
                s.push_str(",\n");
            }
        }
    }

    s.push_str(&(indent + "}"));

    s
}

fn format_string<S: AsRef<str>>(s: S) -> String {
    "\"".to_string() + s.as_ref() + "\""
}
